### ISSUE TITLE
Calculated field not giving expected result

### ISSUE THREAD

**Issue by Felipe-Hub** [ironhack-labs/lab-lod-expressions-dashboards#1]
@sandrabosk 
Apparently { FIXED [clnt_age (group)]: AVG([Bal]) } - [Bal] } doesn't work as expected, maybe something like { FIXED [Client Age]: AVG([Bal]) } - { FIXED [Client Id]: AVG([Bal]) } should work better.

**Comment by ironhack-edu** [comment]
@haggarw3 adding you to be in the loop. Thank you!

**Comment by ironhack-edu** [comment]
Closed with [commit: 2f18d83baf34bf7994db4d9dc4f505733b673729](https://github.com/ironhack-labs/lab-lod-expressions-dashboards/commit/2f18d83baf34bf7994db4d9dc4f505733b673729)
